#!/usr/bin/env python3
"""Retain exact prepared generated bytes for offline diagnostics, never publish.

Replay uses a trusted code checkout and the verified archive's generated files.
The descriptor preserves the collection identity; it grants no publication or
freshness authority. Private caches, transport logs, and environment files are
never included. No Git index, object, ref, or source timestamp is written.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import tarfile
import tempfile
from typing import Any

from vllm import dashboard_state as state


ARCHIVE_NAME = "candidate.tar"
DESCRIPTOR_NAME = "candidate-descriptor.json"
MAX_DESCRIPTOR_BYTES = 256 * 1024
ALLOWED_SUFFIXES = frozenset({".json", ".jsonl", ".md", ".txt"})


def _validation_outcomes(value: object) -> dict[str, dict[str, Any]]:
    if not isinstance(value, dict) or set(value) != {"live_audit", "deterministic_tests"}:
        raise state.DashboardStateError("Candidate validation proof is malformed")
    result = {}
    failed = False
    for name, row in value.items():
        if (
            not isinstance(row, dict) or set(row) != {"outcome", "exit_code"}
            or not isinstance(row.get("outcome"), str)
            or row["outcome"] not in {"success", "failure", "cancelled", "skipped"}
            or (row["exit_code"] is not None and (
                type(row["exit_code"]) is not int or not 0 <= row["exit_code"] <= 255
            ))
        ):
            raise state.DashboardStateError("Candidate validation proof is malformed")
        failed = failed or row["outcome"] == "failure" or (row["exit_code"] or 0) > 0
        result[name] = dict(row)
    if not failed:
        raise state.DashboardStateError("Healthy candidates do not need a diagnostic archive")
    return result


def _safe_path(path: str) -> None:
    state._safe_relative_path(path, label="diagnostic candidate path")
    parts = PurePosixPath(path).parts
    if any(part.startswith(".") for part in parts) or PurePosixPath(path).suffix not in ALLOWED_SUFFIXES:
        raise state.DashboardStateError("Candidate diagnostics refuse cache, environment, or raw files")


def _identity(payload: bytes) -> dict[str, Any]:
    return {
        "bytes": len(payload),
        "sha256": hashlib.sha256(payload).hexdigest(),
        "git_oid": hashlib.sha1(b"blob " + str(len(payload)).encode() + b"\0" + payload).hexdigest(),
    }


def _private_write(path: Path, payload: bytes) -> None:
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(fd, "wb") as stream:
        stream.write(payload)
        stream.flush()
        os.fsync(stream.fileno())


def _archive_hash(path: Path, limit: int) -> tuple[int, str]:
    before = path.lstat()
    if path.is_symlink() or not path.is_file() or before.st_size > limit:
        raise state.DashboardStateError("Candidate archive is not a bounded regular file")
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
    after = path.lstat()
    if (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns) != (
        after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns
    ):
        raise state.DashboardStateError("Candidate archive changed while reading")
    return before.st_size, digest.hexdigest()


def _archive_limit(policy: state.StatePolicy) -> int:
    # The source byte envelope is unchanged. Reserve bounded tar headers,
    # padding, and long-path records separately from captured source bytes.
    return policy.max_tree_bytes + (policy.max_files + 1) * 4096 + 10240


def verify_capture(directory: Path, policy: state.StatePolicy) -> dict[str, Any]:
    """Verify exact archive membership and bytes without extracting anything."""
    descriptor_path = directory / DESCRIPTOR_NAME
    if (
        descriptor_path.is_symlink() or not descriptor_path.is_file()
        or descriptor_path.stat().st_size > MAX_DESCRIPTOR_BYTES
    ):
        raise state.DashboardStateError("Candidate descriptor is not a regular file")
    with descriptor_path.open("rb") as descriptor_stream:
        raw = descriptor_stream.read(MAX_DESCRIPTOR_BYTES + 1)
    if len(raw) > MAX_DESCRIPTOR_BYTES:
        raise state.DashboardStateError("Candidate descriptor exceeds its byte bound")
    descriptor = state._decode_json(raw, label="candidate descriptor")
    expected_keys = {
        "schema_version", "diagnostic_only", "publication_accepted", "phase",
        "code_sha", "generation_id", "generated_at", "source_refs", "manifest",
        "generated_file_count", "generated_bytes", "index_entries_sha256", "archive",
        "validation_outcomes",
    }
    if (
        not isinstance(descriptor, dict) or set(descriptor) != expected_keys
        or type(descriptor.get("schema_version")) is not int or descriptor["schema_version"] != 1
        or descriptor.get("diagnostic_only") is not True
        or descriptor.get("publication_accepted") is not False
        or descriptor.get("phase") != "prepared-collected-candidate"
        or not isinstance(descriptor.get("index_entries_sha256"), str)
        or not re.fullmatch(r"[0-9a-f]{64}", descriptor["index_entries_sha256"])
    ):
        raise state.DashboardStateError("Candidate descriptor is invalid")
    _validation_outcomes(descriptor["validation_outcomes"])
    archive_path = directory / ARCHIVE_NAME
    size, digest = _archive_hash(archive_path, _archive_limit(policy))
    if descriptor["archive"] != {"name": ARCHIVE_NAME, "bytes": size, "sha256": digest}:
        raise state.DashboardStateError("Candidate archive checksum disagrees")
    payloads: dict[str, bytes] = {}
    total = 0
    with tarfile.open(archive_path, "r:") as archive:
        for member in archive:
            _safe_path(member.name)
            if (
                member.name in payloads or not member.isfile() or member.mode != 0o600
                or member.size > policy.max_blob_bytes or len(payloads) >= policy.max_files
                or set(member.pax_headers) - {"path"}
            ):
                raise state.DashboardStateError("Candidate archive member is invalid")
            total += member.size
            if total > policy.max_tree_bytes:
                raise state.DashboardStateError("Candidate source bytes exceed the state envelope")
            stream = archive.extractfile(member)
            if stream is None:
                raise state.DashboardStateError("Candidate archive member is unreadable")
            payloads[member.name] = stream.read(member.size + 1)
            if len(payloads[member.name]) != member.size:
                raise state.DashboardStateError("Candidate archive member size disagrees")
    manifest_bytes = payloads.get(policy.manifest_path)
    if manifest_bytes is None or descriptor["manifest"] != _identity(manifest_bytes):
        raise state.DashboardStateError("Candidate manifest identity disagrees")
    manifest = state._normalize_canonical_manifest(manifest_bytes, policy)
    expected_paths = {*manifest["generated_files"], policy.manifest_path}
    if set(payloads) != expected_paths:
        raise state.DashboardStateError("Candidate archive file inventory disagrees")
    for path, proof in manifest["generated_files"].items():
        actual = _identity(payloads[path])
        if any(actual[key] != proof[key] for key in actual):
            raise state.DashboardStateError("Candidate file byte proof disagrees")
    for key in ("code_sha", "generation_id", "generated_at", "source_refs"):
        if descriptor[key] != manifest[key]:
            raise state.DashboardStateError("Candidate collection identity disagrees")
    if (
        type(descriptor["generated_file_count"]) is not int
        or descriptor["generated_file_count"] != len(manifest["generated_files"])
        or type(descriptor["generated_bytes"]) is not int
        or descriptor["generated_bytes"] != total - len(manifest_bytes)
    ):
        raise state.DashboardStateError("Candidate byte accounting disagrees")
    return descriptor


def capture_candidate(
    root: Path, output: Path, *, policy: state.StatePolicy,
    expected_code_sha: str, expected_generation_id: str,
    validation_outcomes: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    """Copy only the fully verified prepared index into an immutable diagnostic."""
    root, output = root.resolve(), output.absolute()
    outcomes = _validation_outcomes(validation_outcomes)
    if output.is_symlink() or output.exists() or output.resolve().is_relative_to(root):
        raise state.DashboardStateError("Use an unused diagnostic directory outside the workspace")
    state._assert_generated_worktree_paths_are_safe(root, policy)
    state._assert_generated_worktree_is_staged(root, policy)
    manifest = state.validate_index(root, policy, expected_code_sha=expected_code_sha)
    if manifest["generation_id"] != expected_generation_id:
        raise state.DashboardStateError("Candidate generation differs from the expected run")
    entries = state._index_entries(root)
    manifest_entry = entries[policy.manifest_path]
    manifest_bytes = state._cat_blob(root, manifest_entry)
    if state._normalize_canonical_manifest(manifest_bytes, policy) != manifest:
        raise state.DashboardStateError("Candidate index changed before capture")
    paths = sorted({*manifest["generated_files"], policy.manifest_path})
    for path in paths:
        _safe_path(path)
    stage = Path(tempfile.mkdtemp(prefix="candidate-diagnostic-", dir=output.parent))
    try:
        archive_path = stage / ARCHIVE_NAME
        fd = os.open(archive_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "wb") as stream:
            with tarfile.open(fileobj=stream, mode="w", format=tarfile.PAX_FORMAT) as archive:
                for path in paths:
                    payload = state._cat_blob(root, entries[path])
                    if path != policy.manifest_path:
                        proof = manifest["generated_files"][path]
                        actual = _identity(payload)
                        if any(actual[key] != proof[key] for key in actual):
                            raise state.DashboardStateError("Candidate changed during capture")
                    item = tarfile.TarInfo(path)
                    item.size, item.mode = len(payload), 0o600
                    archive.addfile(item, io.BytesIO(payload))
            stream.flush()
            os.fsync(stream.fileno())
        size, digest = _archive_hash(archive_path, _archive_limit(policy))
        descriptor = {
            "schema_version": 1, "diagnostic_only": True, "publication_accepted": False,
            "phase": "prepared-collected-candidate",
            "validation_outcomes": outcomes,
            **{key: manifest[key] for key in ("code_sha", "generation_id", "generated_at", "source_refs")},
            "manifest": _identity(manifest_bytes),
            "generated_file_count": len(manifest["generated_files"]),
            "generated_bytes": sum(proof["bytes"] for proof in manifest["generated_files"].values()),
            "index_entries_sha256": hashlib.sha256(json.dumps(
                {path: [entry.mode, entry.object_id] for path, entry in sorted(entries.items())},
                sort_keys=True, separators=(",", ":"),
            ).encode()).hexdigest(),
            "archive": {"name": ARCHIVE_NAME, "bytes": size, "sha256": digest},
        }
        encoded = (json.dumps(descriptor, sort_keys=True, indent=2) + "\n").encode()
        if len(encoded) > MAX_DESCRIPTOR_BYTES:
            raise state.DashboardStateError("Candidate descriptor exceeds its byte bound")
        _private_write(stage / DESCRIPTOR_NAME, encoded)
        verify_capture(stage, policy)
        if state.validate_index(root, policy, expected_code_sha=expected_code_sha) != manifest:
            raise state.DashboardStateError("Candidate index changed during capture")
        state._assert_generated_worktree_is_staged(root, policy)
        if output.exists() or output.is_symlink():
            raise state.DashboardStateError("Diagnostic destination already exists")
        os.rename(stage, output)
        return descriptor
    finally:
        if stage.exists():
            shutil.rmtree(stage)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=state.ROOT)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--expected-code-sha", required=True)
    parser.add_argument("--expected-generation-id", required=True)
    outcomes = ("success", "failure", "cancelled", "skipped")
    parser.add_argument("--live-audit-outcome", choices=outcomes, required=True)
    parser.add_argument("--live-audit-exit-code", default="")
    parser.add_argument("--test-outcome", choices=outcomes, required=True)
    parser.add_argument("--test-exit-code", default="")
    args = parser.parse_args()
    os.environ["GIT_NO_LAZY_FETCH"] = "1"
    os.environ["GIT_OPTIONAL_LOCKS"] = "0"
    os.environ["GIT_NO_REPLACE_OBJECTS"] = "1"
    try:
        def exit_code(value: str) -> int | None:
            if value == "":
                return None
            if not re.fullmatch(r"\d{1,3}", value) or int(value) > 255:
                raise state.DashboardStateError("Validation exit code is malformed")
            return int(value)

        descriptor = capture_candidate(
            args.root, args.output, policy=state.load_policy(args.root / "config/dashboard_state.json"),
            expected_code_sha=args.expected_code_sha, expected_generation_id=args.expected_generation_id,
            validation_outcomes={
                "live_audit": {"outcome": args.live_audit_outcome, "exit_code": exit_code(args.live_audit_exit_code)},
                "deterministic_tests": {"outcome": args.test_outcome, "exit_code": exit_code(args.test_exit_code)},
            },
        )
    except (state.DashboardStateError, OSError, tarfile.TarError) as exc:
        print(json.dumps({"captured": False, "error_type": type(exc).__name__}))
        return 1
    print(json.dumps({"captured": True, "generation_id": descriptor["generation_id"],
                      "files": descriptor["generated_file_count"], "archive_bytes": descriptor["archive"]["bytes"]}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
